version: "2"
services: 
  zentao:
    image: idoop/zentao:latest
    container_name: zentao
    ports:
      - "80:80"
      - "3306:3306"
    # if web response code: 310 ERR_TOO_MANY_REDIRECTS, please use host mode.
#    network_mode: "host"
    environment:
    # specifies you own account and password.
      USER: "admin"
      PASSWD: "Admin@2018"
      BIND_ADDRESS: "false"
    volumes:
    # specifies the path replace "./data".
      - ./data:/opt/zbox/
    restart: always
